const TestEvent = {
  type: 'family',
  id: 5491086,
  datetime_utc: '2021-10-24T07:30:00',
  venue: {
    state: 'NY',
    name_v2: 'Old Bethpage Village Restoration',
    postal_code: '11804',
    name: 'Old Bethpage Village Restoration',
    links: [],
    timezone: 'America/New_York',
    url: 'https://seatgeek.com/venues/old-bethpage-village-restoration/tickets',
    score: 0.39,
    location: {
      lat: 40.7704,
      lon: -73.444,
    },
    address: '1303 Round Swamp Road',
    country: 'US',
    has_upcoming_events: true,
    num_upcoming_events: 10,
    city: 'Old Bethpage',
    slug: 'old-bethpage-village-restoration',
    extended_address: 'Old Bethpage, NY 11804',
    id: 381202,
    popularity: 0,
    access_method: null,
    metro_code: 501,
    capacity: 0,
    display_location: 'Old Bethpage, NY',
  },
  datetime_tbd: false,
  performers: [
    {
      type: 'theater_family',
      name: 'The Great Jack OLantern Blaze',
      image:
        'https://seatgeek.com/images/performers-landscape/the-great-jack-olantern-blaze-40504e/258427/huge.jpg',
      id: 258427,
      images: {
        huge: 'https://seatgeek.com/images/performers-landscape/the-great-jack-olantern-blaze-40504e/258427/huge.jpg',
      },
      divisions: null,
      has_upcoming_events: true,
      primary: true,
      stats: {
        event_count: 31,
      },
      taxonomies: [
        {
          id: 3000000,
          name: 'theater',
          parent_id: null,
          document_source: {
            source_type: 'ELASTIC',
            generation_type: 'FULL',
          },
          rank: 10,
        },
        {
          id: 3050000,
          name: 'family',
          parent_id: 3000000,
          document_source: {
            source_type: 'ELASTIC',
            generation_type: 'FULL',
          },
          rank: 0,
        },
      ],
      image_attribution:
        'https://www.flickr.com/photos/30478819@N08/33015766008/in/photolist-SiuqYY-2aAJ6nb-27tFEJr-TfEqvU-5aFqe6-2fRfscU-5DcTqo-aeB1dg-bwAYdx-2bPCenq-8ARy1R-bEMH74-8AVpGL-8hqR5S-VdZ7nk-jxcedC-22scg7N-9xTeGb-JpxkhQ-aZSDGK-TeZcdy-UyCnMt-KAvtd8-Zs5p3j-dAxQMP-wWQ9yZ-SVBXhi-U6EHKs-2avypie-27tFDtv-28L2Gyd-27tFTRP-266CDAq-55FPdQ-cQMWE3-cQMWJC-23gcZ9w-eUSFKb-o7da-6iS3sK-bdJx7r-4Li5MP-aFafGG-4Li66X-7JPSpe-4faxNq-bVSDK2-bVSCu4-bVSyga-bVSzfF',
      url: 'https://seatgeek.com/the-great-jack-olantern-blaze-tickets',
      score: 0.4,
      slug: 'the-great-jack-olantern-blaze',
      home_venue_id: null,
      short_name: 'The Great Jack OLantern Blaze',
      num_upcoming_events: 31,
      colors: null,
      image_license:
        'https://creativecommons.org/licenses/by/2.0/?ref=ccsearch&atype=rich',
      popularity: 0,
      location: null,
    },
  ],
  is_open: false,
  links: [],
  datetime_local: '2021-10-24T03:30:00',
  time_tbd: true,
  short_title: 'The Great Jack OLantern Blaze - Long Island',
  visible_until_utc: '2021-10-25T04:00:00',
  stats: {
    listing_count: null,
    average_price: null,
    lowest_price_good_deals: null,
    lowest_price: null,
    highest_price: null,
    visible_listing_count: null,
    dq_bucket_counts: null,
    median_price: null,
    lowest_sg_base_price: null,
    lowest_sg_base_price_good_deals: null,
  },
  taxonomies: [
    {
      id: 3000000,
      name: 'theater',
      parent_id: null,
      rank: 10,
    },
    {
      id: 3050000,
      name: 'family',
      parent_id: 3000000,
      rank: 0,
    },
  ],
  url: 'https://seatgeek.com/the-great-jack-olantern-blaze-long-island-tickets/family/2021-10-24-3-30-am/5491086',
  score: 0,
  announce_date: '2021-09-08T00:00:00',
  created_at: '2021-09-08T16:02:42',
  date_tbd: false,
  title: 'The Great Jack OLantern Blaze - Long Island',
  popularity: 0,
  description: '',
  status: 'normal',
  access_method: null,
  event_promotion: null,
  announcements: {
    checkout_disclosures: {
      messages: [
        {
          text: 'All purchases are 100% guaranteed. Prices set by the seller may be above or below face value.',
        },
      ],
    },
  },
  conditional: false,
  enddatetime_utc: null,
  themes: [],
  domain_information: [],
};

export default TestEvent;
