const TestVenues = [
  {
    state: 'NY',
    name_v2: 'Madison Square Garden',
    postal_code: '10001',
    name: 'Madison Square Garden',
    links: [],
    timezone: 'America/New_York',
    url: 'https://seatgeek.com/venues/madison-square-garden/tickets',
    score: 1,
    location: {
      lat: 40.7509,
      lon: -73.9943,
    },
    address: '4 Pennsylvania Plaza',
    country: 'US',
    has_upcoming_events: true,
    num_upcoming_events: 149,
    city: 'New York',
    slug: 'madison-square-garden',
    extended_address: 'New York, NY 10001',
    stats: {
      event_count: 149,
    },
    id: 93,
    popularity: 0,
    access_method: {
      method: 'QRCODE_TM',
      created_at: '2017-10-06T21:43:25Z',
      employee_only: false,
    },
    metro_code: 501,
    capacity: 20000,
    display_location: 'New York, NY',
  },
  {
    state: 'MI',
    name_v2: 'McGuirk Arena',
    postal_code: '48859',
    name: 'McGuirk Arena',
    links: [],
    timezone: 'America/Detroit',
    url: 'https://seatgeek.com/venues/mcguirk-arena-1/tickets',
    score: 0.99,
    location: {
      lat: 43.5907,
      lon: -84.7757,
    },
    address: '1200 South Franklin Street',
    country: 'US',
    has_upcoming_events: true,
    num_upcoming_events: 14,
    city: 'Mount Pleasant',
    slug: 'mcguirk-arena-1',
    extended_address: 'Mount Pleasant, MI 48859',
    stats: {
      event_count: 14,
    },
    id: 4165,
    popularity: 0,
    access_method: null,
    metro_code: 513,
    capacity: 0,
    display_location: 'Mount Pleasant, MI',
  },
  {
    state: 'CA',
    name_v2: 'Oracle Park',
    postal_code: '94107',
    name: 'Oracle Park',
    links: [],
    timezone: 'America/Los_Angeles',
    url: 'https://seatgeek.com/venues/oracle-park/tickets',
    score: 0.99,
    location: {
      lat: 37.7782,
      lon: -122.391,
    },
    address: '24 Willie Mays Plaza',
    country: 'US',
    has_upcoming_events: true,
    num_upcoming_events: 82,
    city: 'San Francisco',
    slug: 'oracle-park',
    extended_address: 'San Francisco, CA 94107',
    stats: {
      event_count: 82,
    },
    id: 22,
    popularity: 0,
    access_method: {
      method: 'PDF417',
      created_at: '2015-06-25T00:00:00Z',
      employee_only: false,
    },
    metro_code: 807,
    capacity: 41503,
    display_location: 'San Francisco, CA',
  },
];

export default TestVenues;
